import './globals.css';
import Navbar from './navbar/page';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col justify-between items-center h-screen">
          <div className=""> {children}</div>
          <div className="flex w-full justify-center  ">
            <Navbar />
          </div>
        </div>
      </body>
    </html>
  );
}
